theme: jekyll-theme-cayman
email: your email
github:
  is_project_page: true
  repository_url: https://github.com/sanchitdilipjain/aws-reinvent-2021-updates
  repository_name: aws-reinvent-2021-updates
  owner_url: https://github.com/sanchitdilipjain
  owner_name: Sanchit Dilip Jain
